name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          DEPLOY_DIR: '/home/ubuntu/node-aws'
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Ensure directory exists
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "mkdir -p $DEPLOY_DIR && ls -ld $DEPLOY_DIR"

          # Sync files
          rsync -avz --progress -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ $EC2_USER@$EC2_HOST:$DEPLOY_DIR

          # Verify sync
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "ls -l $DEPLOY_DIR"

          # Deploy the app
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd $DEPLOY_DIR
            pwd  # Debug: Confirm directory
            ls -l  # Debug: List files
            sudo npm install -g pm2  # Install pm2 globally
            npm install  # Install app dependencies
            pm2 stop node-aws || true
            pm2 delete node-aws || true
            pm2 start npm --name node-aws -- start --dir $DEPLOY_DIR  # Specify working directory
            pm2 save
          EOF

          rm -f private_key.pem